name: Check GitHub commits

on:
  schedule:
    - cron: "0 22 * * *"

jobs:
  check_commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python main.py
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add commit.db fine.db
          git commit -m "Update commit and fine data"
          git push
